% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Econometrics II - Assignment 4}
\author{Uncensored sloths}
\date{27 Jan 2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Econometrics II - Assignment 4},
  pdfauthor={Uncensored sloths},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{lscape}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{question-1}{%
\section{Question 1}\label{question-1}}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Use the Wald estimator to compute the causal effect of a prison
  sentence on the probability of being arrested later.
\end{enumerate}

Since treatment participation \(D_i=1\) (i.e.~a prison sentence) is
likely related to unobserved characteristics,instrumentation using the
random assignment to either judge \(Z_i\) is necessary. Since the
probability of being sentenced to prison is higher for judge Jones,
assignment to Jones when \(Z_i=1\) is treated as the assignment to the
treatment hereinafter. Hence, the Wald estimator reads as:

\[
\hat{\delta}_{Wald}=\frac{\mathrm{E}[Y|Z=1]-\mathrm{E}[Y|Z=0]}{\mathrm{E}[D|Z=1]-\mathrm{E}[D|Z=0]}=\frac{(70\%\cdot40\%+30\%\cdot60\%)-(40\%\cdot20\%+60\%\cdot50\%)}{70\%-40\%}=26.\bar{6}\%
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{((}\FloatTok{0.7}\SpecialCharTok{*}\FloatTok{0.4+0.3}\SpecialCharTok{*}\FloatTok{0.6}\NormalTok{)}\SpecialCharTok{{-}}\NormalTok{(}\FloatTok{0.4}\SpecialCharTok{*}\FloatTok{0.2+0.6}\SpecialCharTok{*}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{/}\NormalTok{(}\FloatTok{0.7{-}0.4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2666667
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What is the interpretation of the estimated effect? And for which
  fraction of the population does this causal effect hold?
\end{enumerate}

Hence, the Wald estimator states that a prison sentence increases the
probability of being arrested later by \(26.\bar{6}\%\). However,
assuming monotonicity this causal effect only holds for compliers,
i.e.~people which would be sentenced to prison by Jones, but not by
Smith. By the monoticity assumption, i.e.~ruling out the existence of
defiers, which would not be sentenced to prison by Jones, but would be
by Smith, the fraction of compliers in the population can be estimated
by the (thus identifiable) fraction of compliers in the sample.

Assuming away defiers, we know that all \(40\%\) of the people sentenced
to the treatment by Smith, i.e.~for which \(D(0)=1\) are always takers.
Moreover, we know that under the non-existence of defiers, all \(30\%\)
of the people not sentenced to the treatment by Jones, i.e.~for which
\(D(1)=0\), are never takers. Hence, assuming that cases are truly
randomly assigned to the judges, this implies that there must be
\(100\%-40\%-30\%=30\%\) compliers in the sample and thus that the
causal effect identified by the Wald estimator holds for (approximately)
\(30\%\) of the population.

There is serious doubt, however, whether the assumption of monotonicity
holds in the application at hand. After all, it seems anything but far
fetched to assume that there are some individuals which are sentenced to
prison by Smith, but not by Jones (conditional on some characteristics),
even though Jones is on average more likely to convict people to prison.
If this is the case, it becomes very difficult to interpret the Wald
estimator as it becomes biased by the presence of defiers (Angrist et
al, 1996). One could, however, still consider alternative assumptions to
validate the interpretation of the Wald estimator outlined above. First,
one could argue along the lines of Angrist et al.~(1996) that the
treatment effect for defiers and compliers is identical. Second, one
could impose the complier-defier assumption brought forward by De
Chaisemartin (2017) and assume that there exists some group of compliers
which has the same size and average treatment effect as the defiers such
that the bias brought along by defiers vanishes. However, if these
assumptions do not reasonably hold, the interpretation of the Wald
estimator is rather inconclusive.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Explain what an always taker is in this setting and which fraction of
  the population are always takers?
\end{enumerate}

People that are sentenced to prison by both judges should be considered
as always takers in this setting. Hence, for Smith they make up \(40\%\)
of the sample once we assume away defiers since compliers and never
takers are never sentenced to prison by Smith. For Jones, they are part
of the \(70\%\) together with the compliers as only the never takers are
never sentenced to prison with Jones as a judge under the monotonicity
assumption. Consequently, always takers constitute \(40\%\) of the
sample/population assuming monotonicity.

\hypertarget{question-2}{%
\section{Question 2}\label{question-2}}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Perform a power calculation for the number of students that the
  teacher should include in the field experiment.
\end{enumerate}

Performing a power calculation, the number of students that need to be
included in the field experiment can be calculated using the customary
formula, where (i) \(MDE=0.1\) since the teacher thinks the passing rate
is 10 percentage points lower for the treatment group, (ii) treatment
intensity \(p=0.5\) by assumption since this minimizes the necessary
sample size c.p., (iii) \(\sigma=0.5(1-0.5)=0.25\) since the teacher
assumes that 50\% of students in the control group will pass the exam,
and \(t_{1-\alpha/2}=t_{0.975}=1.960\) and \(t_{1-q}=t_{0.3}=-0.524\) as
specified by the teacher.

\[
n=\left(\frac{t_{1-\alpha/2}-t_{1-q}}{MDE}\right)^2\frac{\sigma}{p(1-p)}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MDE\_target }\OtherTok{\textless{}{-}} \FloatTok{0.1}
\NormalTok{t\_q }\OtherTok{=} \SpecialCharTok{{-}}\FloatTok{0.524}
\NormalTok{t\_alpha }\OtherTok{\textless{}{-}} \FloatTok{1.960}
\NormalTok{p }\OtherTok{=} \FloatTok{0.5}
\NormalTok{sigma }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\FloatTok{{-}0.5}\NormalTok{)}\SpecialCharTok{*}\FloatTok{0.5}
\NormalTok{n\_target }\OtherTok{=}\NormalTok{ ((t\_alpha }\SpecialCharTok{{-}}\NormalTok{ t\_q)}\SpecialCharTok{/}\NormalTok{MDE\_target)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{((sigma)}\SpecialCharTok{/}\NormalTok{(p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)))}
\FunctionTok{ceiling}\NormalTok{(n\_target)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 618
\end{verbatim}

Hence, the teacher should include 618 students in the field experiment.
The question whether the teacher should include any students in the
experiment, i.e.~whether to run it all, in light of ethical
considerations is left to the interested reader.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  The teacher assumes that 20\% of the students randomized in the
  treatment group will actually have breakfast. How does this change the
  number of students required to participate in the field experiment?
\end{enumerate}

Since the teacher does not expect full compliance, the number of
necessary students should be computed as follows, where the compliance
rate in the treatment group \(r_t=0.8\) since the teacher assumes that
20\% of the students randomized in the treatment group will actually
have breakfast and the treatment intensity in the control group
\(r_c=0\) since the teacher assumes that all people in the control group
will have breakfast.

\[
n=\left(\frac{t_{1-\alpha/2}-t_{1-q}}{MDE(r_t-r_c)}\right)^2\frac{\sigma}{p(1-p)}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt }\OtherTok{\textless{}{-}} \FloatTok{0.8}
\NormalTok{rc }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{n\_complience }\OtherTok{=}\NormalTok{ ((t\_alpha }\SpecialCharTok{{-}}\NormalTok{ t\_q)}\SpecialCharTok{/}\NormalTok{(MDE\_target}\SpecialCharTok{*}\NormalTok{(rt }\SpecialCharTok{{-}}\NormalTok{ rc)))}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{((sigma)}\SpecialCharTok{/}\NormalTok{(p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)))}
\FunctionTok{ceiling}\NormalTok{(n\_complience)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 965
\end{verbatim}

As one would expect intuitively, non-compliance in the treatment group
weakens the power of the experiment and thus increases the number of
students that is required to participate to 965 (more than 50\%) as not
everyone complies with the treatment.

\hypertarget{question-3}{%
\section{Question 3}\label{question-3}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load data}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"assignment4.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Compute for the children assigned to the control group the variance in
  flu incidence. If the researcher aims at reducing flu incidence by
  \(0.05\), how many children should participate in the randomized
  experiment.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data[data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\StringTok{\textquotesingle{}flu\textquotesingle{}}\NormalTok{])}
\NormalTok{sigma }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{q)}\SpecialCharTok{*}\NormalTok{q}
\NormalTok{sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.235434
\end{verbatim}

To variance in flu incidence of the children assigned to the control
group is approximately \(0.2354\).

As the researcher aims to reduce the flue incidence by \(0.05\), we set
our MDE value to \(-0.05\). \(80\%\) of the children are supposed to get
the flu shot which is why we set p to \(0.8\). The variance of the
Bernoulli variable corresponds to the variance in flu incidence of the
children assigned to the control group. Setting the power to \(70\%\)
and the significance level to \(5\%\), we get a required sample size of
3632 children.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MDE\_target }\OtherTok{\textless{}{-}} \SpecialCharTok{{-}}\FloatTok{0.05}
\NormalTok{t\_q }\OtherTok{\textless{}{-}} \SpecialCharTok{{-}}\FloatTok{0.524}
\NormalTok{t\_alpha }\OtherTok{\textless{}{-}} \FloatTok{1.960}
\NormalTok{p }\OtherTok{\textless{}{-}} \FloatTok{0.8}
\NormalTok{n\_flu }\OtherTok{=}\NormalTok{ ((t\_alpha }\SpecialCharTok{{-}}\NormalTok{ t\_q)}\SpecialCharTok{/}\NormalTok{MDE\_target)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{((sigma)}\SpecialCharTok{/}\NormalTok{(p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)))}
\FunctionTok{ceiling}\NormalTok{(n\_flu)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3632
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Compute which fraction of the children in the treatment group actually
  received a flu shot. What is the implication for the power analysis of
  the experiment?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rt }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data[data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{\textquotesingle{}flushot\textquotesingle{}}\NormalTok{])}
\NormalTok{rt}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6679552
\end{verbatim}

Approximately, \(66.8\%\) of children in the treatment actually received
a flu shot.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rc }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data[data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\StringTok{\textquotesingle{}flushot\textquotesingle{}}\NormalTok{])}
\NormalTok{rc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{q)}\SpecialCharTok{*}\NormalTok{q}
\NormalTok{n\_flu }\OtherTok{=}\NormalTok{ ((t\_alpha }\SpecialCharTok{{-}}\NormalTok{ t\_q)}\SpecialCharTok{/}\NormalTok{(MDE\_target}\SpecialCharTok{*}\NormalTok{(rt }\SpecialCharTok{{-}}\NormalTok{ rc)))}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{((sigma)}\SpecialCharTok{/}\NormalTok{(p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)))}
\FunctionTok{ceiling}\NormalTok{(n\_flu)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8140
\end{verbatim}

Not every child that was supposed to get a flu shot, got a flu shot
which is why we set the rate in the treatment group to
\(r_t \approx 0.668\). There are no children who were not supposed to
get treatment but got a flu shot which is why the the treatment
intensity in the control group equals zero (\(r_c = 0\)). Including
these aspects into our calculation of the sample size, we find that the
necessary sample size increases to 8140 children. Hence, if we do not
increase the sample, this would decrease the power of the design
considerably.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Make a table with summary statistics for (1) the control group, (2)
  the treated treatment group, and (3) the untreated treatment group.
  What do you conclude?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\NormalTok{treatedT }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{c}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{flushot}\SpecialCharTok{==}\DecValTok{1}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{untreatedT }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{c}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{flushot}\SpecialCharTok{==}\DecValTok{0}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{treatment }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{treatedT}\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{untreatedT}\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{balance }\OtherTok{\textless{}{-}} \FunctionTok{balance\_table}\NormalTok{(data[, }\SpecialCharTok{!}\FunctionTok{names}\NormalTok{(data) }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"treatgroup"}\NormalTok{, }\StringTok{"flushot"}\NormalTok{, }\StringTok{"treatedT"}\NormalTok{, }\StringTok{"untreatedT"}\NormalTok{)], }\StringTok{"treatment"}\NormalTok{)}
\NormalTok{balance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 7 x 6
##   variables1  Media_control1 Media_trat1 Media_trat2 p_value1 p_value2
##   <chr>                <dbl>       <dbl>       <dbl>    <dbl>    <dbl>
## 1 agemother           26.1        26.6        24.9   1.22e-12 2.46e-52
## 2 educmother          12.3        12.5        11.8   5.86e- 6 1.31e-28
## 3 flu                  0.621       0.401       0.675 1.54e-79 1.83e- 5
## 4 genderchild          0.508       0.503       0.501 6.80e- 1 6.22e- 1
## 5 housincome        2270.       2374.       2111.    1.45e- 5 4.90e-10
## 6 married              0.957       0.977       0.939 1.83e- 5 1.24e- 3
## 7 nationality          0.278       0.239       0.341 1.33e- 4 3.00e- 7
\end{verbatim}

Except for the gender of the children, which is equally distributed
among the control, the treated treatment and the untreated treatment
groups, we have significant differences in terms of the age of the
mother, the education of the mother, the household income, the
proportion of marriages and the proportion of children with a migration
background. The mothers in the untreated treatment group are younger
than the mothers in the control group and the treated treatment group.
Moreover, they have less years of education, the households have a lower
income and a higher share of the mothers is not married. Last but not
least, a higher share of the children is native in the untreated
treatment group.

In the treated treatment group, on the other side, the mothers are older
than in the control group. They have more years of education, a higher
household income and higher share of the mothers is married. Further, a
lower share of the children is native. The treated treatment group has a
considerably lower share of children who got the flu while the untreated
treatment group has a higher share than the control group.

Considering these evident differences between the control and the
untreated treatment group, we can conclude that getting the flu shot is
not the only aspect that impacts the probability of getting the flu as
otherwise the untreated treatment group would not have significantly
more flu infections on average than the control group. One reason why
this group has more flu infections than the control group might be that
the children have worse access to healthy diet as the mothers earn less
on average and are more often single mothers (assuming that they raise
their children alone as a result of being not married). This would have
a negative effect on their immune system, making the children more prone
to get the flu.

Further, we have to consider that whether a child receives the assigned
treatment or not does not only relate to the treatment assignment but
also to the age of the mother, the education of the mother, the
household income, the marital status of the mother and the nationality
of the child as there are considerable differences between the treated
and untreated treatment group. However, to be able to make more
inferences on that, we would have to do further estimations first.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Estimate this model using OLS. Next, include subsequently the
  individual characteristics. What do you learn from these regressions?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1\_robust }\OtherTok{\textless{}{-}} \FunctionTok{rlm}\NormalTok{(flu }\SpecialCharTok{\textasciitilde{}}\NormalTok{ flushot, }\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(data, data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{1}\NormalTok{))}
\NormalTok{model2\_robust }\OtherTok{\textless{}{-}} \FunctionTok{rlm}\NormalTok{(flu }\SpecialCharTok{\textasciitilde{}}\NormalTok{ flushot }\SpecialCharTok{+}\NormalTok{ genderchild }\SpecialCharTok{+}\NormalTok{ nationality }\SpecialCharTok{+}\NormalTok{ agemother }\SpecialCharTok{+}\NormalTok{ educmother }\SpecialCharTok{+}\NormalTok{ married }
                     \SpecialCharTok{+}\NormalTok{ housincome, }\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(data, data}\SpecialCharTok{$}\NormalTok{treatgroup }\SpecialCharTok{==} \DecValTok{1}\NormalTok{))}

\FunctionTok{stargazer}\NormalTok{(model1\_robust, model2\_robust)}
\end{Highlighting}
\end{Shaded}

\% Table created by stargazer v.5.2.2 by Marek Hlavac, Harvard
University. E-mail: hlavac at fas.harvard.edu \% Date and time: Sun, Jan
30, 2022 - 18:41:49

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
\cline{2-3} 
\\[-1.8ex] & \multicolumn{2}{c}{flu} \\ 
\\[-1.8ex] & (1) & (2)\\ 
\hline \\[-1.8ex] 
 flushot & $-$0.274$^{***}$ & $-$0.164$^{***}$ \\ 
  & (0.010) & (0.010) \\ 
  & & \\ 
 genderchild &  & 0.016$^{*}$ \\ 
  &  & (0.009) \\ 
  & & \\ 
 nationality &  & 0.092$^{***}$ \\ 
  &  & (0.010) \\ 
  & & \\ 
 agemother &  & $-$0.048$^{***}$ \\ 
  &  & (0.002) \\ 
  & & \\ 
 educmother &  & $-$0.030$^{***}$ \\ 
  &  & (0.003) \\ 
  & & \\ 
 married &  & $-$0.024 \\ 
  &  & (0.025) \\ 
  & & \\ 
 housincome &  & 0.00001 \\ 
  &  & (0.00000) \\ 
  & & \\ 
 Constant & 0.675$^{***}$ & 2.200$^{***}$ \\ 
  & (0.008) & (0.045) \\ 
  & & \\ 
\hline \\[-1.8ex] 
Observations & 10,089 & 10,089 \\ 
Residual Std. Error & 0.594 (df = 10087) & 0.602 (df = 10081) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{2}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

We estimate two OLS models with robust standard errors. The first model
include whether a child received the flushot as its only regressor. The
other model also includes individuals characteristics such as the gender
and the migration background of the child as well as the age, the years
of education, the marital status of the mother and the household income.
As the researcher wants to focus only on those children randomized in
the treatment group, we only use the data of the children who were
assigned treatment.

In both model the flushot is estimated to decrease the probability of
getting the flu significantly. However, the estimated impact is
considerably lower when we include individual characteristics. Hence,
our estimation is not robust. Further, the age of the mother and the
education of the mother have a significant, negative effect while the
child being native has a significant positive effect. Being a girl also
has a significant positive effect but only at \(10\%\). The F test shows
us that the estimators are jointly significant.

As the estimations for the flushot differ considerably between the two
models, we have to consider that the model specification may be wrong or
that underlying assumptions do not hold (e.g.~heteroskedasticity or
endogeneity of the regressors).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{linearHypothesis}\NormalTok{(model2\_robust, }\FunctionTok{c}\NormalTok{(}\StringTok{"genderchild=0"}\NormalTok{, }\StringTok{"nationality=0"}\NormalTok{, }\StringTok{"agemother=0"}\NormalTok{, }\StringTok{"educmother=0"}\NormalTok{, }
                                  \StringTok{"married=0"}\NormalTok{, }\StringTok{"housincome=0"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear hypothesis test
## 
## Hypothesis:
## genderchild = 0
## nationality = 0
## agemother = 0
## educmother = 0
## married = 0
## housincome = 0
## 
## Model 1: restricted model
## Model 2: flu ~ flushot + genderchild + nationality + agemother + educmother + 
##     married + housincome
## 
##   Res.Df Df      F    Pr(>F)    
## 1  10087                        
## 2  10081  6 254.08 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Use 2SLS to estimate \(\beta_1\) and check the robustness with respect
  to adding individual characteristics.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model3 }\OtherTok{\textless{}{-}} \FunctionTok{feols}\NormalTok{(flu }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{|}\NormalTok{ flushot }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treatgroup, data)}
\FunctionTok{summary}\NormalTok{(model3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## TSLS estimation, Dep. Var.: flu, Endo.: flushot, Instr.: treatgroup
## Second stage: Dep. Var.: flu
## Observations: 12,583 
## Standard-errors: IID 
##              Estimate Std. Error  t value  Pr(>|t|)    
## (Intercept)  0.620690   0.009705  63.9530 < 2.2e-16 ***
## fit_flushot -0.192779   0.016227 -11.8802 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## RMSE: 0.484649   Adj. R2: 0.059242
## F-test (1st stage), flushot: stat = 5,016.2, p < 2.2e-16 , on 1 and 12,581 DoF.
##                  Wu-Hausman: stat =    17.1, p = 2.237e-5, on 1 and 12,580 DoF.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model4 }\OtherTok{\textless{}{-}} \FunctionTok{feols}\NormalTok{(flu }\SpecialCharTok{\textasciitilde{}}\NormalTok{ genderchild }\SpecialCharTok{+}\NormalTok{ nationality }\SpecialCharTok{+}\NormalTok{ agemother }\SpecialCharTok{+}\NormalTok{ educmother }\SpecialCharTok{+}\NormalTok{ married }
                \SpecialCharTok{+}\NormalTok{ housincome }\SpecialCharTok{|}\NormalTok{ flushot }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treatgroup, data)}
\FunctionTok{summary}\NormalTok{(model4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## TSLS estimation, Dep. Var.: flu, Endo.: flushot, Instr.: treatgroup
## Second stage: Dep. Var.: flu
## Observations: 12,583 
## Standard-errors: IID 
##                Estimate Std. Error    t value  Pr(>|t|)    
## (Intercept)  2.15266853 0.04010533  53.675370 < 2.2e-16 ***
## fit_flushot -0.19827462 0.01508642 -13.142589 < 2.2e-16 ***
## genderchild  0.01342733 0.00804823   1.668358   0.09527 .  
## nationality  0.09024013 0.00913374   9.879864 < 2.2e-16 ***
## agemother   -0.04628152 0.00163287 -28.343613 < 2.2e-16 ***
## educmother  -0.02731668 0.00278890  -9.794798 < 2.2e-16 ***
## married     -0.02848121 0.02181911  -1.305333   0.19180    
## housincome   0.00000357 0.00000423   0.844801   0.39824    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## RMSE: 0.451201   Adj. R2: 0.184224
## F-test (1st stage), flushot: stat = 5,400.9   , p < 2.2e-16 , on 1 and 12,575 DoF.
##                  Wu-Hausman: stat =     3.5763, p = 0.058633, on 1 and 12,574 DoF.
\end{verbatim}

We estimate two models using the assignment to treatment as an
instrumental variable for the regressor flushot. As in the previous
subquestion, the first model includes flushot as its only regressors in
the second stage regression and the second model includes the flushot
and individual characteristics. In both models, we get an estimation of
approximately \(-0.2\) for the flushot. Further, in both models the
estimation is significant at \(0.1\%\). Hence, the estimation for the
flushot is robust with respect to adding individual characteristics.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  Estimate the first-stage regression using OLS. Are you afraid of a
  weak instruments problem?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{first\_stage }\OtherTok{\textless{}{-}} \FunctionTok{rlm}\NormalTok{(flushot }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treatgroup }\SpecialCharTok{+}\NormalTok{ genderchild }\SpecialCharTok{+}\NormalTok{ nationality }\SpecialCharTok{+}\NormalTok{ agemother }\SpecialCharTok{+}\NormalTok{ educmother }\SpecialCharTok{+}\NormalTok{ married }
                   \SpecialCharTok{+}\NormalTok{ housincome, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{stargazer}\NormalTok{(first\_stage)}
\end{Highlighting}
\end{Shaded}

\% Table created by stargazer v.5.2.2 by Marek Hlavac, Harvard
University. E-mail: hlavac at fas.harvard.edu \% Date and time: Sun, Jan
30, 2022 - 18:41:49

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & flushot \\ 
\hline \\[-1.8ex] 
 treatgroup & 0.691$^{***}$ \\ 
  & (0.010) \\ 
  & \\ 
 genderchild & 0.0001 \\ 
  & (0.008) \\ 
  & \\ 
 nationality & $-$0.089$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
 agemother & 0.030$^{***}$ \\ 
  & (0.002) \\ 
  & \\ 
 educmother & 0.013$^{***}$ \\ 
  & (0.003) \\ 
  & \\ 
 married & 0.075$^{***}$ \\ 
  & (0.022) \\ 
  & \\ 
 housincome & 0.00001$^{***}$ \\ 
  & (0.00000) \\ 
  & \\ 
 Constant & $-$1.015$^{***}$ \\ 
  & (0.041) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 12,583 \\ 
Residual Std. Error & 0.451 (df = 12575) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

We estimate the first stage including the instrumental variable and all
exogenous variables as regressors. The assignment to treatment increases
the probability of getting a flushot. The same goes for the age, the
marital status and the years of education of the mother, although their
impact is considerably lower than in the case of the assignment to
treatment. The household income also has a small, positive and
significant effect, while the child being a native has a negative
effect. Hence, we can conclude that children, whose mothers are younger,
have less years of education and are single, were less likely to get the
flushot. On the other hand, children that have a migration background
were more likely to get a flushot.

We do not see an issue with weak instruments here, as the effect of
being in the treatment group is significant at \(0.01\%\). Including the
estimation from the previous subquestion, we can observe that for both
estimations we have a first-stage F statistics above 10. Hence, we have
have evidence that the assignment to the treatment group is not a weak
instrument.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
  Explain why in this case the local average treatment effect is the
  same as the average treatment effect on the treated.
\end{enumerate}

LATE is the local treatment effect of the compliers, so when
\(D(1)-D(0)=1\). ATET is the effect on the treated, so when \(D=1\). D
equals one in four cases. First, the individual was not assigned
treatment but still got the treatment, so \(D(0) = 1\). In this case the
individual is either an always taker or a defier. If the individual was
assigned treatment and got the treatment, so when \(D(1)=1\), then the
individual is either an always taker or a complier.

\[
D_i = 1 
\begin{cases}
  D(0) = 1 & \text{if i is Always Taker or Defier}\\
  D(1) = 1 & \text{if i is Always Taker or Complier}
\end{cases}
\]

Based on the data, we can exclude always takers and defiers completely
because no one of the control group received a flushot despite not being
assigned the treatment. Therefore, we have only compliers and never
takers in our sample.

As ATET only considers individuals that got treatment but is not able to
differentiate between defiers, compliers and always takers, ATET usually
does not equal LATE. However, in our case, we were able to exclude the
possibility of always takers and defiers in our sample. Hence, ATET only
considers compliers here and therefore is the same as LATE.

Note that the existence of never takers in our sample is not an issue
because neither LATE nor ATET considers never takers.

Mathematically, this means that \(D(1)-D(0) = D(1)\) as \(D(0)=0\).
Hence, we can write: \[
LATE = E(Y_1^* - Y_0^*|D(1)-D(0)=1) = E(Y_1^* - Y_0^*|D(1)=1) = E(Y_1^* - Y_0^*|D=1) = ATET
\]

\hypertarget{references}{%
\section{References}\label{references}}

Angrist, J. D., Imbens, G. W., \& Rubin, D. B. (1996). Identification of
causal effects using instrumental variables. Journal of the American
statistical Association, 91(434), 444-455. De Chaisemartin, C. (2017).
Tolerating defiance? Local average treatment effects without
monotonicity. Quantitative Economics, 8(2), 367-396.

\end{document}
